export const defaultTrlLevels = [
  {
    trlLevelNumber: 1,
    trlLevelName: "Research & Exploration",
    subLevels: [
      { subLevelNumber: 1, subLevelName: "Objectives and Goals" },
      { subLevelNumber: 2, subLevelName: "Research Findings" },
      { subLevelNumber: 3, subLevelName: "Market Analysis" },
      { subLevelNumber: 4, subLevelName: "Problem Identification" },
      { subLevelNumber: 5, subLevelName: "Technical Boundaries" },
      { subLevelNumber: 6, subLevelName: "Concept Development" },
      { subLevelNumber: 7, subLevelName: "Stakeholder Engagement" },
      { subLevelNumber: 8, subLevelName: "Next Steps" },
      { subLevelNumber: 9, subLevelName: "Challenges and Barriers" },
    ],
  },
  {
    trlLevelNumber: 2,
    trlLevelName: "Concept Development",
    subLevels: [
      { subLevelNumber: 1, subLevelName: "Objectives and Goals" },
      { subLevelNumber: 2, subLevelName: "Problem Definition" },
      { subLevelNumber: 3, subLevelName: "Concept Formulation" },
      { subLevelNumber: 4, subLevelName: "Literature Review" },
      { subLevelNumber: 5, subLevelName: "Hypothesis Development" },
      { subLevelNumber: 6, subLevelName: "Preliminary Modeling" },
      { subLevelNumber: 7, subLevelName: "Initial Feasibility Studies" },
      { subLevelNumber: 8, subLevelName: "Stakeholder Engagement" },
      { subLevelNumber: 9, subLevelName: "Planned Actions for Advancement" },
      { subLevelNumber: 10, subLevelName: "Challenges and Barriers" },
    ],
  },
  {
    trlLevelNumber: 3,
    trlLevelName: "Initial Feasibility",
    subLevels: [
      { subLevelNumber: 1, subLevelName: "Objectives and Goals" },
      { subLevelNumber: 2, subLevelName: "Experimental Design" },
      { subLevelNumber: 3, subLevelName: "Proof of Concept" },
      { subLevelNumber: 4, subLevelName: "Data Collection" },
      { subLevelNumber: 5, subLevelName: "Performance Metrics" },
      { subLevelNumber: 6, subLevelName: "Integration Studies" },
      { subLevelNumber: 7, subLevelName: "Risk Assessment" },
      { subLevelNumber: 8, subLevelName: "Stakeholder Feedback" },
      { subLevelNumber: 9, subLevelName: "Next Steps" },
      { subLevelNumber: 10, subLevelName: "Challenges and Barriers" },
    ],
  },
  {
    trlLevelNumber: 4,
    trlLevelName: "Prototype Development",
    subLevels: [
      { subLevelNumber: 1, subLevelName: "Objectives and Goals" },
      { subLevelNumber: 2, subLevelName: "Prototype Specifications" },
      { subLevelNumber: 3, subLevelName: "Development Process" },
      { subLevelNumber: 4, subLevelName: "Integration of Components" },
      { subLevelNumber: 5, subLevelName: "Testing and Validation" },
      { subLevelNumber: 6, subLevelName: "User Feedback" },
      { subLevelNumber: 7, subLevelName: "Risk Assessment" },
      { subLevelNumber: 8, subLevelName: "Next Steps for Advancement" },
      { subLevelNumber: 9, subLevelName: "Challenges and Barriers" },
      { subLevelNumber: 10, subLevelName: "Documentation and Reporting" },
    ],
  },
  {
    trlLevelNumber: 5,
    trlLevelName: "Testing & Refinement",
    subLevels: [
      { subLevelNumber: 1, subLevelName: "Objectives and Goals" },
      { subLevelNumber: 2, subLevelName: "Prototype Overview" },
      { subLevelNumber: 3, subLevelName: "Testing Environment" },
      { subLevelNumber: 4, subLevelName: "Testing Methodologies" },
      { subLevelNumber: 5, subLevelName: "Performance Metrics" },
      { subLevelNumber: 6, subLevelName: "Results and Findings" },
      { subLevelNumber: 7, subLevelName: "User Feedback" },
      { subLevelNumber: 8, subLevelName: "Risk Assessment" },
      { subLevelNumber: 9, subLevelName: "Next Steps for Advancement" },
      { subLevelNumber: 10, subLevelName: "Challenges and Barriers" },
    ],
  },
  {
    trlLevelNumber: 6,
    trlLevelName: "Pilot Deployment",
    subLevels: [
      { subLevelNumber: 1, subLevelName: "Objectives and Goals" },
      { subLevelNumber: 2, subLevelName: "Pilot Deployment Overview" },
      { subLevelNumber: 3, subLevelName: "Testing Methodologies" },
      { subLevelNumber: 4, subLevelName: "Performance Metrics" },
      { subLevelNumber: 5, subLevelName: "User Engagement" },
      { subLevelNumber: 6, subLevelName: "Risk Management" },
      { subLevelNumber: 7, subLevelName: "Data Collection and Analysis" },
      { subLevelNumber: 8, subLevelName: "Next Steps for Advancement" },
      { subLevelNumber: 9, subLevelName: "Challenges and Barriers" },
      { subLevelNumber: 10, subLevelName: "Documentation and Reporting" },
    ],
  },
  {
    trlLevelNumber: 7,
    trlLevelName: "Operational Testing",
    subLevels: [
      { subLevelNumber: 1, subLevelName: "Objectives and Goals" },
      { subLevelNumber: 2, subLevelName: "Testing Environment" },
      { subLevelNumber: 3, subLevelName: "Testing Methodologies" },
      { subLevelNumber: 4, subLevelName: "Performance Metrics" },
      { subLevelNumber: 5, subLevelName: "Integration and Compatibility" },
      { subLevelNumber: 6, subLevelName: "User Engagement and Feedback" },
      { subLevelNumber: 7, subLevelName: "Risk Management" },
      { subLevelNumber: 8, subLevelName: "Data Collection and Analysis" },
      { subLevelNumber: 9, subLevelName: "Next Steps for Advancement" },
      { subLevelNumber: 10, subLevelName: "Challenges and Barriers" },
    ],
  },
  {
    trlLevelNumber: 8,
    trlLevelName: "Final Validation",
    subLevels: [
      { subLevelNumber: 1, subLevelName: "Objectives and Goals" },
      { subLevelNumber: 2, subLevelName: "Validation Process Overview" },
      { subLevelNumber: 3, subLevelName: "Performance Metrics" },
      {
        subLevelNumber: 4,
        subLevelName: "Compliance and Regulatory Requirements",
      },
      { subLevelNumber: 5, subLevelName: "Data Collection and Analysis" },
      { subLevelNumber: 6, subLevelName: "User Engagement and Feedback" },
      { subLevelNumber: 7, subLevelName: "Risk Management" },
      { subLevelNumber: 8, subLevelName: "Next Steps for Advancement" },
      { subLevelNumber: 9, subLevelName: "Challenges and Barriers" },
      { subLevelNumber: 10, subLevelName: "Documentation and Reporting" },
    ],
  },
  {
    trlLevelNumber: 9,
    trlLevelName: "Full Deployment & Maintenance",
    subLevels: [
      { subLevelNumber: 1, subLevelName: "Objectives and Goals" },
      { subLevelNumber: 2, subLevelName: "Deployment Overview" },
      { subLevelNumber: 3, subLevelName: "Performance Monitoring" },
      { subLevelNumber: 4, subLevelName: "Data Collection and Analysis" },
      { subLevelNumber: 5, subLevelName: "User Engagement and Feedback" },
      { subLevelNumber: 6, subLevelName: "Maintenance Plans" },
      { subLevelNumber: 7, subLevelName: "Risk Management" },
      { subLevelNumber: 8, subLevelName: "Support Structure" },
      { subLevelNumber: 9, subLevelName: "Next Steps for Future Development" },
      { subLevelNumber: 10, subLevelName: "Challenges and Barriers" },
    ],
  },
];

